### ISSUE TITLE
有没有 QQ撒，想问下 MNNetwork 详细网络请求方式。

### ISSUE THREAD

**Issue by PublicWorld** [zxc3731/NewSwiftProjectDemo#1]

**Comment by zxc3731** [comment]
其实这个在项目里面已经有一个例子的，你看看 “Login(登录注册)”这个模块下面的VC和VM类，还有简书也有比较详细的讲解（http://www.jianshu.com/users/841883f31e69/latest_articles）

**Comment by PublicWorld** [comment]
有没有办法解决每次使用 RxSwift 要频繁导入 #if !RX_NO_MODULE
    import RxSwift
    import RxCocoa
#endif 的问题。

**Comment by zxc3731** [comment]
这个我暂时还没找到方法。你可以将其加入代码块，那样就方便点
